UPDATE posts SET title = 'Επιστημονική Δημοσίευση στο νομικό περιοδικό Δίκαιο Τεχνολογίας & Επικοινωνίας (ΔΙΤΕ) - Google Ads & Trademarks' WHERE slug = 'adwords-google-trademark';
UPDATE posts SET title = 'Επιστημονική Δημοσίευση στο νομικό περιοδικό ΣΥΝΗΓΟΡΟΣ της Νομικής Βιβλιοθήκης' WHERE slug = 'blog-post';
UPDATE posts SET title = 'Το περιστατικό με τη γιαγιά στα Lidl, μια φήμη και ένα δίδαγμα' WHERE slug = 'branding-marketing';
UPDATE posts SET title = 'Συμβολή στο συλλογικό έργο "Δίκαιο Σημάτων - Ερμηνεία κατ'' άρθρο του Ν. 4679/2020"' WHERE slug = 'dikaio-simatwn';
UPDATE posts SET title = 'Δικηγόροι Εμπορικών Σημάτων - Εκδήλωση' WHERE slug = 'emporiko-sima-dikigoroi';
UPDATE posts SET title = 'Το εμπορικό σήμα ως περιουσιακό στοιχείο της επιχείρησης: οι αριθμοί, η προστασία και δύο προτάσεις' WHERE slug = 'emporiko-sima-dikigoros-kataxorisi-katoxurosi';
UPDATE posts SET title = 'Milan AC: Ένας αγώνας που δεν κερδήθηκε και ένα δίδαγμα για την κατοχύρωση σήματος της Ε.Ε.' WHERE slug = 'emporiko-sima-EE-EUIPO';
UPDATE posts SET title = 'Ο κίνδυνος σύγχυσης στο δίκαιο του σήματος - Μονογραφία' WHERE slug = 'emporiko-sima-eidikos';
UPDATE posts SET title = 'Κατοχύρωση εμπορικού σήματος: Η απόφαση HYAL του Γενικού Δικαστηρίου της ΕΕ' WHERE slug = 'emporiko-sima-kataxwrish';
UPDATE posts SET title = 'Turkaegean: Ο Ατατούρκ και 11 σκέψεις' WHERE slug = 'emporiko-sima-onoma-turkaegean-euipo-katoxurosi';
UPDATE posts SET title = 'Η Μεγάλη Έξοδος από την αγορά της Ρωσίας και το όπλο της Διανοητικής Ιδιοκτησίας' WHERE slug = 'emporiko-sima-patentes-polemos';
UPDATE posts SET title = 'Εμπορικό Σήμα: Σεμινάριο εξειδικευμένου περιεχομένου' WHERE slug = 'emporikosimaseminario';
UPDATE posts SET title = 'Κατοχύρωση ευρωπαϊκού και εθνικού σήματος: ο απαραίτητος έλεγχος πριν την κατάθεση στον EUIPO και τον ΟΒΙ' WHERE slug = 'EUIPO-OBI-SIMA-ELEGXOS-DIKIGOROS';
UPDATE posts SET title = 'Scientific Publication in European Intellectual Property Review (Sweet & Maxwell)' WHERE slug = 'european-intellectual-property-review';
UPDATE posts SET title = 'Scientific Publication in Journal of Intellectual Property Law & Practice (Oxford University Press)' WHERE slug = 'journal-of-intellectual-property-law';
UPDATE posts SET title = 'Μια υπόθεση ελληνικών συμφερόντων: η κατοχύρωση εμπορικού σήματος και το συχνότερο λάθος κατά την καταχώριση' WHERE slug = 'kataxorisi-simatos-elegxos';
UPDATE posts SET title = 'Κατάθεση εμπορικού σήματος: Η διαδικασία και γιατί η κατοχύρωση ονόματος συμφέρει την επιχείρηση' WHERE slug = 'kataxwrisi-onoma-katoxurosi-sima-logo';
UPDATE posts SET title = 'EUIPO - La Liga σημειώσατε 1' WHERE slug = 'kataxwrisi-sima-euipo';
UPDATE posts SET title = 'Οι σύγχρονες μελέτες για την κατοχύρωση εμπορικού σήματος (trademark)' WHERE slug = 'katoxirosi-simatos-dhlwsh';
UPDATE posts SET title = 'Κατοχύρωση domain name ως εμπορικό σήμα: ένας απλός τρόπος για την αποφυγή δυσάρεστων εκπλήξεων' WHERE slug = 'katoxurwsi-domain-name-kai-emporiko-sima';
UPDATE posts SET title = 'Scientific Publication in Kluwer Trademark Blog (Wolters Kluwer N.V.)' WHERE slug = 'kluwer-trademark-blog-wolters-kluwer-nv';
UPDATE posts SET title = 'Αλλαγή παραδείγματος από το Γενικό Δικαστήριο της ΕΕ: χρήσιμα συμπεράσματα για τον ΟΒΙ' WHERE slug = 'OBI-SIMATA-EUIPO';
UPDATE posts SET title = 'Κατάθεση εμπορικού σήματος: Σε τι εξυπηρετεί και όλα όσα πρέπει να γνωρίζετε' WHERE slug = 'onoma-simata-kataxorisi-dikigoros';
UPDATE posts SET title = 'Προσβολή trademark: Η συχνότερη περίπτωση και γιατί συμφέρει η κατοχύρωση σήματος (Part I)' WHERE slug = 'paraviasi-sima-dikigoros-prostasia';
UPDATE posts SET title = 'Η προσβολή του εμπορικού σήματος: Η ευρύτερη δυνατή προστασία - το σήμα φήμης' WHERE slug = 'prostasia-sima-trademark';
UPDATE posts SET title = 'Φάκελος: Κατάθεση σήματος - Πότε προσβάλλεται το εμπορικό μου σήμα;' WHERE slug = 'prosvoli-emporikou-simatos';
UPDATE posts SET title = 'Ο πόλεμος στην Ουκρανία, τα ξένα κράτη και η Πέππα το γουρουνάκι' WHERE slug = 'russia-polemos-trademark';
UPDATE posts SET title = 'Προσβολή trademark: Η συχνότερη περίπτωση (Part II) - Κίνδυνος συσχέτισης' WHERE slug = 'sima-dikigoros-prosvoli-katoxurosi';
UPDATE posts SET title = 'Μπορώ να έχω δικαίωμα σε συγκεκριμένη ένδειξη χωρίς καταχώριση σήματος;' WHERE slug = 'sima-epwnumia-domain-kataxwrisi';
UPDATE posts SET title = 'Η καταχώριση εμπορικού σήματος της ΕΕ (EUTM) και η άμυνα σε πιθανή ανακοπή' WHERE slug = 'sima-tis-europaikis-enwsis';
UPDATE posts SET title = 'Η κατοχύρωση του νέου εμπορικού σήματος της Juventus και η σημασία της νεότερης νομολογίας' WHERE slug = 'trademark-simata-dikigoros-juv';
UPDATE posts SET title = 'Όταν το Netflix επιχείρησε να καταχωρίσει το χαρακτηριστικό ηχητικό έναρξης ως εμπορικό σήμα της ΕΕ' WHERE slug = 'trademark-netflix-euipo';
