backend:
  name: github
  repo: mikemorakis/trademark
  branch: master

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: 'el'

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Author", name: "author", widget: "string", default: "Giannis Psarakis" }
      - { label: "Slug (URL)", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
